// 气体状态方
export const M30 = {
  id: "PHY-M30",
  title: "气体状态方",
  module: "热学",
  chapter: "热学",
  difficulty: 2,
  subtitle: "pV=nRT，理想气体状态方",
  estimatedMinutes: 20,
  positioning: { core: "内容建设中",
  essence: "内容建设中",
  keyInsight: "内容建设中 " },
  principle: "## {title}\n\n内容正在编写中。\n\n**核心公式**：详见下方工具箱",
  variations: { basic: [], advanced: [], challenge: [] },
  knowledgeNetwork: { parents: [], children: [], related: [], coreFormula: "" },
  methodology: { approach: "内容建设中",
    decisionTree: ["第一步：分析已知", "第二步：选择公式", "第三步：代入计算"], commonPitfalls: ["易错"] },
  selfCheck: { questions: [], confidenceLevel: 1 },
  lifeApplication: "内容建设中",
}
