// 机械
export const M37 = {
  id: "PHY-M37",
  title: "机械",
  module: "机械",
  chapter: "机械",
  difficulty: 2,
  subtitle: "横波纵波，波形图与振动图",
  estimatedMinutes: 20,
  positioning: { core: "内容建设中",
  essence: "内容建设中",
  keyInsight: "内容建设中 " },
  principle: "## {title}\n\n内容正在编写中",
  variations: { basic: [], advanced: [], challenge: [] },
  knowledgeNetwork: { parents: [], children: [], related: [], coreFormula: "" },
  methodology: { approach: "内容建设中",
    decisionTree: ["第一步：分析已知", "第二步：选择公式", "第三步：代入计算"], commonPitfalls: ["易错"] },
  selfCheck: { questions: [], confidenceLevel: 1 },
  lifeApplication: "内容建设中",
}
